### PR TITLE
Measure remaining time stats

### PR DESCRIPTION
**Pull request by JKamsker**

### CODE REVIEW

**Comment by richardbang83** [comment]
pretty awesome !! 
You surprise me

**Comment by JKamsker** [comment]
Tbh, im not a js dev .... 
Mainly c# but doing some js for fun inbetween :D

**Comment by JKamsker** [comment]
So weve gotta just merge this one and close the other prs, cause this one is based on the other odes

**Comment by richardbang83** [comment]
Yes, I agree with you..
I will resolve the conflicts and merge them soon..
And I want to say that I'm also not js dev, but c# too.
These work are so for fun and to try to learn js.

**Comment by JKamsker** [comment]
Haha nice xD

**Comment by richardbang83** [comment]
I want to mention that the new repository is going on..
It will have some new features such as downloading multiple sessions and file informations..
It, of course, will be merged with the features done by you..
I hope to present you soon,,

**Comment by JKamsker** [comment]
Cant wait for your work :)

**Comment by JKamsker** [comment]
What new repository?

**Comment by richardbang83** [comment]
> What new repository?

It is based on another repository which is for multiple download and is modified for working with pluralsight..
So, I'm working on new repository registered to mine

**Comment by JKamsker** [comment]
Ah very awesome, would you accept me as a contributor?

**Comment by sahilsehwag** [comment]
That would be great Richard, if we could combine the new features that you are mentioning with this project as well

**Comment by sahilsehwag** [comment]
Jonas, if you are interested, we would love to have you as a contributor for this project as well

**Comment by richardbang83** [comment]
> Ah very awesome, would you accept me as a contributor?

Of course, you should come..

**Comment by richardbang83** [comment]
> That would be great Richard, if we could combine the new features that you are mentioning with this project as well

I hope so, but as I mentioned it is mainly based on another repository, we have a lot of work to do..
After organizing a little, I notice you too
And we can decide how to deal with this issue.

**Pull request merged**
