### PR TITLE
Update script.js

### PR DESCRIPTION
**Pull request by richardbang83**
Make it more stable and optimize the downloading process a little

### CODE REVIEW

**Comment by richardbang83** [comment]
Please check this commit for handling exception that could be happened while downloading them..
@JKamsker ###

**Comment by richardbang83** [comment]
You must be careful not to merge with commit.
It is under test with throw exception at line 472.

**Comment by richardbang83** [comment]
Any comment for this request?

**Comment by sahilsehwag** [comment]
I have covid, do what seems best to you.

**Comment by richardbang83** [comment]
> Wed, Apr 21, 2021, 8:03 AM richardbang83 ***@***.***> wrote: Any comment for this request? —

I'm so sorry to hear that. I hope you get better soon.
As you wish, I will try to do my best.

**Pull request merged**
