### PR TITLE
Updated script to use the script url and regex based on new video player

### PR DESCRIPTION
**Pull request by tanushshukla**

### CODE REVIEW

**Comment by mjishnu** [comment]
- added fix for #63

@tanushshukla i have made a PR in you fork  after merging this PR should fix #63 and #67

**Comment by tanushshukla** [comment]
thanks! I will merge it in.

**Review by sahilsehwag — APPROVED** [review]

**Comment by sureshmohan251** [comment]
@sahilsehwag Can you please share the link of latest version crx file or Zip file. Its not available [here](https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/releases)

**Comment by mjishnu** [comment]
> @sahilsehwag Can you please share the link of latest version crx file or Zip file. Its not available [here](https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/releases)

just clone the repo or download the source as zip and install it as unpackaged in chrome/whatever chromium based browser.

**Comment by sureshmohan251** [comment]
> > @sahilsehwag Can you please share the link of latest version crx file or Zip file. Its not available [here](https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/releases)
> 
> just clone the repo or download the source as zip and install it as unpackaged in chrome/whatever chromium based browser.

Thanks @sahilsehwag. I Have installed the extension but unable to download any videos. Getting the below error.. 

image

**Comment by mjishnu** [comment]
> > > @sahilsehwag Can you please share the link of latest version crx file or Zip file. Its not available [here](https://github.com/sahilsehwag/pluralsight-downloader-chrome-extension/releases)
> > 
> > 
> > just clone the repo or download the source as zip and install it as unpackaged in chrome/whatever chromium based browser.
> 
> Thanks @sahilsehwag. I have installed the extension but it downloads only first few videos.

do you have a subscription if yes make sure you are logged in to pluralsight. this tool need subscription to work. also don't close the tab from which you initiated the download until its completed

**Comment by g-h-mac** [comment]
@sahilsehwag  I find the new version of the extension broken today. Trying to download a course using Chrome and this extension and when it goes to download a video it tries to download some xml file  and not an mp4. The result is "Failed no file"

**Pull request merged**
